function init(self)
	self.url = msg.url(".")
end

local function count_table(t)
	local count = 0
	for _, _ in pairs(t) do
		count = count + 1
	end
	return count
end

local MSG = hash("whatever")
local count = 0
local urls = {}
function update(self, dt)
	msg.post("/main#other", MSG, { url = self.url, payload = count })
	urls[self.url] = count
	count = count + 1
	print("main.urls", count_table(urls))
end
